name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install buildozer + deps
        run: |
          python -m pip install --upgrade pip
          pip install "kivy[base]==2.3.1" buildozer pymunk pillow
      # ▼ 新增：安装 host 侧 Cython（与 p4a 兼容的 0.29.x）
      - name: Install Cython
        run: pip install "cython==0.29.36"

      - name: Build debug APK
        run: buildozer -v android debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flappy-debug-apk
          path: bin/*-debug*.apk
